# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2021
#  @credits:    AKAE
#
#  @license:    GPLv3
#  @maintainer: Nuno Brum
#  @email:      nuno.brum@gmail.com
#
#  @file:       unittest.yml
#  @date:       2023-08-09
#
#  @brief:      runs unit test
#
# ************************************************************************


name: Unittest

on: [push, pull_request]

jobs:
  Unittest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64'   # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
      - name: Test sweep_iterators.py
        if: always()
        run: |
          python ./unittests/sweep_iterators_unittest.py
      - name: Test spicelib
        if: always()
        run: |
          python ./unittests/test_spicelib.py
      - name: Test QSpice Raw Reader
        if: always()
        run: |
          python ./unittests/test_qspice_rawread.py
      - name: Test Spice Editor
        if: always()
        run: |
          python ./unittests/test_spice_editor.py
      - name: Test Asc_Editor
        if: always()
        run: |
          python ./unittests/test_asc_editor.py
      - name: Test Qsch Editor
        if: always()
        run: |
          python ./unittests/test_qsch_editor.py
      - name: Test RawReaders
        if: always()
        run: |
          python ./unittests/test_rawreaders.py          
